export const INBOX = 'inboxes';
export const SENT = 'sents';
export const ADMIN = 'Administrator';
export const SUPERUSER = 'Superuser';
export const USER = 'User';
export const DESC = 'DESC';
export const ASC = 'ASC';
export const TABS = ['time', 'profile', 'mail'];
export const DEFAULT_TAB = 'user';
